---
title: "Plotting_changes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R

```{r libraries}
library(ggplot2)
library(datasets)
library(dplyr)
```

## Plot changes in Miles per gallons v/s Weight  

```{r Plot1}
req_colors <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


mtcars <- mtcars %>% mutate(Transmission = ifelse(am ==0 , "automatic","manual")) %>%
  mutate(Engine = ifelse (vs == 0, "v-shaped","straight")) %>%
  mutate(gears = ifelse( gear == 3, "3gears", ifelse( gear==4, "4gears", "5gears")))



mg <- ggplot(mtcars, 
             aes(x = mpg, y = wt, 
                 color = Transmission, 
                 shape = Transmission)) + scale_colour_manual(values = req_colors) +
  geom_point()

myPlot <- mg + facet_grid(Engine ~ gears) +
  theme_bw() + xlab("Miles per gallon (mpg)") +
  ylab("Weight (wt)") + theme(legend.position = c(0.85,0.9), axis.text.x = element_text(angle=45), legend.background = element_rect(colour = NA, fill = NA))
  
ggsave(filename="plot1.pdf", plot=myPlot)
```

## Plot changes in Engline displament v/s Highway miles per gallon

```{r Plot1}
ds <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +scale_color_manual(values=req_colors) +
  geom_smooth(aes(fill = class)) + scale_fill_manual( values = req_colors)
myPlot2 <- ds+ theme_bw() + xlab("Engine displacement (litres)") + ylab("Highway miles per gallon") +
   theme(legend.position = c(0.85,0.8), axis.text.x = element_text(angle=45), legend.background = element_rect(colour = NA, fill = NA))

ggsave(filename="plot2.pdf", plot=myPlot2)
```

