---
title: "Assignment2"
author: "Neelakshi Soni"
date: "January 16, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R Markdown

Base R

```{r base}
findc <- function(vec){
  l <- length(vec)
  mat <- matrix(c(1:l), 1, l) %*% diag(l)
  ones <- which(matrix(vec, l, 1) %*% mat == 1)
  check <- t(replicate(length(ones), c(1:l)))
  apply(check, 2, function(x){
    ones[which.min(abs(ones - x))]
  })
}

vec <- c(0,0,1,0,0,0,0,1,1,0,0,0,0,0)
findc(vec)
vec 
file <- (cbind(as.data.frame(vec), as.data.frame(findc(vec))))
colnames(file) <- c("value","closest")

```


Tidyverse 


```{r tidyverse, echo=FALSE}


library(tidyverse)
library(dplyr)

vec <- c(0,0,1,0,0,0,0,1,1,0,0,0,0,0)
file1 <- vec %>% as.tibble() %>% mutate(mat = matrix(c(1:length(vec)), 1, length(vec)) %*% diag(length(vec)))
ones <- which(matrix(file1$value, length(vec), 1) %*% file1$mat == 1)


file1 <- vec %>% as.tibble() %>% 
mutate(closest=(apply(t(replicate(length(ones), c(1:length(vec)))), 2, function(x){
  ones[which.min(abs(ones - x))]
})))
```
